apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-deployment
  labels:
    app: ml-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app-deployment
        image: ml-docker-app:latest
        resources:
          requests:
            cpu: "100m"
            memory: "100M"
          limits:
            cpu: "1000m"
            memory: "100M"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000